/**
 * Splits index.css into modular files under src/styles/legacy/
 * Run: node scripts/split-css.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const src = path.join(__dirname, "../src/index.css");
const outDir = path.join(__dirname, "../src/styles/legacy");

const raw = fs.readFileSync(src, "utf8");
const lines = raw.split("\n");

// Find section markers
const markers = [];
for (let i = 0; i < lines.length; i++) {
  if (lines[i].match(/^\/\* —— /)) {
    const name = lines[i]
      .replace(/^\/\* —— /, "")
      .replace(/ —— \*\/$/, "")
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
    markers.push({ line: i, name });
  }
}

if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

// Preamble (before first marker) — base resets only, skip :root (in tokens.css)
const firstMarker = markers[0]?.line ?? lines.length;
const preamble = lines.slice(0, firstMarker).join("\n");

// Strip duplicate :root block from preamble
const preambleClean = preamble.replace(/:root\s*\{[\s\S]*?\}\s*/m, "").trim();

const files = [];
for (let m = 0; m < markers.length; m++) {
  const start = markers[m].line;
  const end = m + 1 < markers.length ? markers[m + 1].line : lines.length;
  let chunk = lines.slice(start, end).join("\n").trim();
  const fname = `${String(m + 1).padStart(2, "0")}-${markers[m].name}.css`;
  fs.writeFileSync(path.join(outDir, fname), chunk + "\n");
  files.push(fname);
}

// Write minimal base from preamble (no :root)
if (preambleClean) {
  fs.writeFileSync(
    path.join(outDir, "00-base.css"),
    `/* Resets and utilities migrated from index.css */\n${preambleClean}\n`,
  );
  files.unshift("00-base.css");
}

// Generate barrel import
const barrel = `/* Auto-generated by scripts/split-css.mjs — do not edit by hand */\n${files.map((f) => `@import "./legacy/${f}";`).join("\n")}\n`;
fs.writeFileSync(path.join(__dirname, "../src/styles/legacy.css"), barrel);

console.log(`Split ${markers.length} sections into ${outDir}`);
console.log(`Barrel: styles/legacy.css (${files.length} imports)`);
