// Package patterns owns the durable motion pattern and program library,
// authoring transforms, import/export, and visible preference feedback.
package patterns

import (
	"errors"

	"github.com/mapledaemon/MagicHandy/internal/motion"
)

const (
	// OriginBuiltin identifies code-generated catalog content.
	OriginBuiltin = "builtin"
	// OriginUser identifies directly authored content.
	OriginUser = "user"
	// OriginGenerated identifies app-generated user content.
	OriginGenerated = "generated"
	// OriginImported identifies finite content imported from a file.
	OriginImported = "imported"

	// PatternFileSchema is the share-file schema for one loop pattern.
	PatternFileSchema = "magichandy.pattern.v1"
	// ProgramFileSchema is the share-file schema for one finite program.
	ProgramFileSchema = "magichandy.program.v1"

	maxPatterns      = 250
	maxPrograms      = 100
	maxPatternPoints = 256
	maxProgramPoints = 4096
	// MaxImportBytes bounds pattern/program upload bodies at the HTTP edge.
	MaxImportBytes      = 8 << 20
	maxContentNameChars = 80
	maxDescriptionChars = 400
	maxContentDuration  = int64(24 * 60 * 60 * 1000)

	autoDisableKey = "patterns.auto_disable"
)

var (
	// ErrPatternNotFound reports an unknown pattern identifier.
	ErrPatternNotFound = errors.New("pattern not found")
	// ErrProgramNotFound reports an unknown program identifier.
	ErrProgramNotFound = errors.New("program not found")
	// ErrBuiltinPattern protects built-in content from edit/delete operations.
	ErrBuiltinPattern = errors.New("built-in pattern content is read-only")
	// ErrFeedbackOrder prevents undo from overwriting a newer preference edit.
	ErrFeedbackOrder = errors.New("only the latest feedback for a pattern can be undone")
)

// Pattern is one persisted library entry.
type Pattern struct {
	ID          string              `json:"id"`
	Name        string              `json:"name"`
	Description string              `json:"description,omitempty"`
	Origin      string              `json:"origin"`
	Kind        string              `json:"kind"`
	Enabled     bool                `json:"enabled"`
	Weight      float64             `json:"weight"`
	CycleMillis int64               `json:"cycle_ms"`
	Points      []motion.CurvePoint `json:"points"`
	// PreviewSamples are generated by the backend playback sampler and are not
	// persisted as a second motion representation.
	PreviewSamples []motion.CurvePoint `json:"preview_samples"`
	Tags           []string            `json:"tags"`
	CreatedAt      string              `json:"created_at"`
	UpdatedAt      string              `json:"updated_at"`
}

// Definition converts a stored row to engine-owned semantic content.
func (p Pattern) Definition() motion.PatternDefinition {
	return motion.PatternDefinition{
		ID:          motion.PatternID(p.ID),
		Name:        p.Name,
		Description: p.Description,
		Kind:        p.Kind,
		CycleMillis: p.CycleMillis,
		Points:      append([]motion.CurvePoint(nil), p.Points...),
		Tags:        append([]string(nil), p.Tags...),
	}
}

// Program is finite content kept distinct from repeatable patterns.
type Program struct {
	ID             string              `json:"id"`
	Name           string              `json:"name"`
	Origin         string              `json:"origin"`
	DurationMillis int64               `json:"duration_ms"`
	Points         []motion.CurvePoint `json:"points"`
	// PreviewSamples are generated by the backend playback sampler and are not
	// persisted as a second motion representation.
	PreviewSamples []motion.CurvePoint `json:"preview_samples"`
	CreatedAt      string              `json:"created_at"`
	UpdatedAt      string              `json:"updated_at"`
}

// Definition converts a stored program to finite engine content.
func (p Program) Definition() motion.ProgramDefinition {
	return motion.ProgramDefinition{
		ID:             p.ID,
		Name:           p.Name,
		DurationMillis: p.DurationMillis,
		Points:         append([]motion.CurvePoint(nil), p.Points...),
	}
}

// Feedback is one visible, reversible preference adjustment.
type Feedback struct {
	ID            int64   `json:"id"`
	PatternID     string  `json:"pattern_id"`
	Rating        int     `json:"rating"`
	WeightBefore  float64 `json:"weight_before"`
	WeightAfter   float64 `json:"weight_after"`
	EnabledBefore bool    `json:"enabled_before"`
	EnabledAfter  bool    `json:"enabled_after"`
	Reverted      bool    `json:"reverted"`
	CreatedAt     string  `json:"created_at"`
	RevertedAt    string  `json:"reverted_at,omitempty"`
}

// Snapshot is the backend-authoritative library workspace state.
type Snapshot struct {
	Patterns    []Pattern  `json:"patterns"`
	Programs    []Program  `json:"programs"`
	Feedback    []Feedback `json:"feedback"`
	AutoDisable bool       `json:"auto_disable"`
}

// Summary is the compact polling state; large point arrays stay off /api/state.
type Summary struct {
	PatternCount        int  `json:"pattern_count"`
	EnabledPatternCount int  `json:"enabled_pattern_count"`
	ProgramCount        int  `json:"program_count"`
	AutoDisable         bool `json:"auto_disable"`
}

// PatternInput is authoring/import content before persistence assigns an ID.
type PatternInput struct {
	Name          string              `json:"name"`
	Description   string              `json:"description,omitempty"`
	Kind          string              `json:"kind"`
	CycleMillis   int64               `json:"cycle_ms"`
	Points        []motion.CurvePoint `json:"points"`
	Tags          []string            `json:"tags,omitempty"`
	SimplifyError float64             `json:"simplify_error,omitempty"`
}

// PatternPatch contains optional row/content changes.
type PatternPatch struct {
	Name        *string              `json:"name,omitempty"`
	Description *string              `json:"description,omitempty"`
	Kind        *string              `json:"kind,omitempty"`
	Enabled     *bool                `json:"enabled,omitempty"`
	Weight      *float64             `json:"weight,omitempty"`
	CycleMillis *int64               `json:"cycle_ms,omitempty"`
	Points      *[]motion.CurvePoint `json:"points,omitempty"`
	Tags        *[]string            `json:"tags,omitempty"`
}

// PreviewResult returns the exact sparse curve and backend sampler output.
type PreviewResult struct {
	Points          []motion.CurvePoint `json:"points"`
	Samples         []motion.CurvePoint `json:"samples"`
	CycleMillis     int64               `json:"cycle_ms"`
	OriginalCount   int                 `json:"original_count"`
	SimplifiedCount int                 `json:"simplified_count"`
}

// ImportResult distinguishes imported loops from finite programs.
type ImportResult struct {
	Kind         string   `json:"kind"`
	Pattern      *Pattern `json:"pattern,omitempty"`
	Program      *Program `json:"program,omitempty"`
	GapsStripped int      `json:"gaps_stripped"`
}

// CurationChoice is prompt-safe enabled pattern metadata.
type CurationChoice struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description,omitempty"`
	Tags        []string `json:"tags"`
	Weight      float64  `json:"weight"`
}

type patternFile struct {
	Schema      string              `json:"schema"`
	Name        string              `json:"name"`
	Description string              `json:"description,omitempty"`
	Kind        string              `json:"kind"`
	CycleMillis int64               `json:"cycle_ms"`
	Points      []motion.CurvePoint `json:"points"`
	Tags        []string            `json:"tags,omitempty"`
}

type programFile struct {
	Schema         string              `json:"schema"`
	Name           string              `json:"name"`
	DurationMillis int64               `json:"duration_ms"`
	Points         []motion.CurvePoint `json:"points"`
}
